REM exp_dtsx_project.bat MO-STG-SSRS01 aino_ndm cert D:\temp\export_4_report 2017-05-01_12
@ECHO OFF
ECHO.

SETLOCAL enabledelayedexpansion

SET SERVER_NAME=%1
SET UTIL_DB_NAME=ssis_utils
SET SSIS_CATALOG_FOLDER=%2
SET SSIS_CATALOG_PROJECT=%3
SET WORK_BASE=%4
SET TIMESTAMP=%5
SET SCRIPT_PATH=%WORK_BASE%\scripts
SET SVC_PATH=%WORK_BASE%\report\%SSIS_CATALOG_FOLDER%_%TIMESTAMP%
SET SVC_DTSX_PATH=%SVC_PATH%\dtsx


SET TARGET_CATALOG_FOLDER_PATH=%SVC_DTSX_PATH%


SET EXP_PROJECT_FILE_NAME=%SSIS_CATALOG_PROJECT%

SET EXP_PROJECT_FULL_FILE_NAME=%EXP_PROJECT_FILE_NAME%.ispac

IF EXIST %TARGET_CATALOG_FOLDER_PATH%\%EXP_PROJECT_FULL_FILE_NAME% DEL /Q %TARGET_CATALOG_FOLDER_PATH%\%EXP_PROJECT_FULL_FILE_NAME%

sqlcmd -S "%SERVER_NAME%" -d "%UTIL_DB_NAME%" -Q "EXECUTE [%UTIL_DB_NAME%].[dbo].[sp_exp_ssis_project] %SSIS_CATALOG_FOLDER%, %SSIS_CATALOG_PROJECT%, %EXP_PROJECT_FILE_NAME%, '%TARGET_CATALOG_FOLDER_PATH%' "

REM remove unzipped direcitory if existed
IF EXIST %TARGET_CATALOG_FOLDER_PATH%\%SSIS_CATALOG_PROJECT% DEL /Q %TARGET_CATALOG_FOLDER_PATH%\%SSIS_CATALOG_PROJECT%

"C:\Program Files\7-Zip\7z.exe" e %TARGET_CATALOG_FOLDER_PATH%\%EXP_PROJECT_FULL_FILE_NAME% -o%TARGET_CATALOG_FOLDER_PATH%\%SSIS_CATALOG_PROJECT% -aoa

GOTO :eof