REM ftp_to_sv.bat mo-stg-ftp-vapp01.rnd.laxino.com ssrs Cc123456 aino_ndm cert D:\temp\export_4_report /sv_files 2017-05-01_12

SET FTP_HOST=%1
SET FTP_USER=%2
SET FTP_PASSWD=%3
SET SVC=%4
SET PROJECT=%5
SET WORK_BASE=%6
SET WORK_SCRIPTS_PATH=%WORK_BASE%\scripts
SET TEMP_CMD_FILE=%WORK_SCRIPTS_PATH%\tmp_ftp_cmd.txt
SET TIMESTAMP=%8


REM SET FTP_LOCAL_BASE_PATH=%
SET LOCAL_SVC_PATH=%WORK_BASE%\report\%SVC%_%TIMESTAMP%

SET REMOTE_BASE_PATH=%7/report
SET REMOTE_SVC_PATH=%REMOTE_BASE_PATH%/tmp_%SVC%

ECHO open %FTP_HOST%>%TEMP_CMD_FILE%
ECHO %FTP_USER%>> %TEMP_CMD_FILE%
ECHO %FTP_PASSWD%>> %TEMP_CMD_FILE%
ECHO prompt>>%TEMP_CMD_FILE%
ECHO ASC>>%TEMP_CMD_FILE%
ECHO mkdir %REMOTE_BASE_PATH% >> %TEMP_CMD_FILE%


ECHO mdelete %REMOTE_SVC_PATH%/dtsx/%PROJECT%/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_SVC_PATH%/dtsx/%PROJECT% >> %TEMP_CMD_FILE%
ECHO mdelete %REMOTE_SVC_PATH%/sp/%PROJECT%/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_SVC_PATH%/sp/%PROJECT% >> %TEMP_CMD_FILE%
ECHO mdelete %REMOTE_SVC_PATH%/rdl/%PROJECT%/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_SVC_PATH%/rdl/%PROJECT% >> %TEMP_CMD_FILE%

ECHO mdelete %REMOTE_SVC_PATH%/dtsx/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_SVC_PATH%/dtsx >> %TEMP_CMD_FILE%
ECHO mdelete %REMOTE_SVC_PATH%/sp/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_SVC_PATH%/sp >> %TEMP_CMD_FILE%
ECHO mdelete %REMOTE_SVC_PATH%/rdl/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_SVC_PATH%/rdl >> %TEMP_CMD_FILE%
ECHO mdelete %REMOTE_SVC_PATH%/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_SVC_PATH% >> %TEMP_CMD_FILE%

ECHO mkdir %REMOTE_SVC_PATH% >> %TEMP_CMD_FILE%
ECHO mkdir %REMOTE_SVC_PATH%/dtsx >> %TEMP_CMD_FILE%
ECHO mkdir %REMOTE_SVC_PATH%/dtsx/%PROJECT% >> %TEMP_CMD_FILE%
ECHO mkdir %REMOTE_SVC_PATH%/sp >> %TEMP_CMD_FILE%
ECHO mkdir %REMOTE_SVC_PATH%/sp/%PROJECT% >> %TEMP_CMD_FILE%
ECHO mkdir %REMOTE_SVC_PATH%/rdl >> %TEMP_CMD_FILE%
ECHO mkdir %REMOTE_SVC_PATH%/rdl/%PROJECT% >> %TEMP_CMD_FILE%

ECHO cd %REMOTE_SVC_PATH%/dtsx/%PROJECT% >> %TEMP_CMD_FILE%
ECHO mput %LOCAL_SVC_PATH%\dtsx\%PROJECT%\*.dtsx >> %TEMP_CMD_FILE%
ECHO cd %REMOTE_SVC_PATH%/sp/%PROJECT% >> %TEMP_CMD_FILE%
ECHO mput %LOCAL_SVC_PATH%\sp\%PROJECT%\*.sql >> %TEMP_CMD_FILE%
ECHO cd %REMOTE_SVC_PATH%/rdl/%PROJECT% >> %TEMP_CMD_FILE%
ECHO mput %LOCAL_SVC_PATH%\rdl\%PROJECT%\*.rdl >> %TEMP_CMD_FILE%


ECHO mdelete %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP%/dtsx/%PROJECT%/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP%/dtsx/%PROJECT% >> %TEMP_CMD_FILE%
ECHO mdelete %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP%/sp/%PROJECT%/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP%/sp/%PROJECT% >> %TEMP_CMD_FILE%
ECHO mdelete %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP%/rdl/%PROJECT%/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP%/rdl/%PROJECT% >> %TEMP_CMD_FILE%

ECHO mdelete %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP%/dtsx/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP%/dtsx >> %TEMP_CMD_FILE%
ECHO mdelete %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP%/sp/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP%/sp >> %TEMP_CMD_FILE%
ECHO mdelete %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP%/rdl/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP%/rdl >> %TEMP_CMD_FILE%
ECHO mdelete %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP%/* >> %TEMP_CMD_FILE%
ECHO rmdir %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP% >> %TEMP_CMD_FILE%


ECHO rename %REMOTE_SVC_PATH% %REMOTE_BASE_PATH%/%SVC%_%TIMESTAMP% >> %TEMP_CMD_FILE%
ECHO quit >> %TEMP_CMD_FILE%

REM Launch FTP and pass it the script
ftp -s:%TEMP_CMD_FILE%

REM Clean up.
DEL %TEMP_CMD_FILE%

GOTO :eof